## Query request
{"query_string": "mr darcy","threshold": 11}
curl -v --http2-prior-knowledge -H "Content-Type: application/json" -X POST -d '{"query_string": "mr darcy","threshold": 11}' localhost:8765/submit/query

## Submit document
{
    "id": 1,
    "name": "austen104",
    "data": "To Mr. Darcy it was welcome intelligence—Elizabeth had been at Netherfield long enough. She attracted him more than he liked—and Miss Bingley was uncivil to _her_, and more teasing than usual to himself. He wisely resolved to be particularly careful that no sign of admiration should _now_ escape him, nothing that could elevate her with the hope of influencing his felicity; sensible that if such an idea had been suggested, his behaviour during the last day must have material weight in confirming or crushing it. Steady to his purpose, he scarcely spoke ten words to her through the whole of Saturday, and though they were at one time left by themselves for half-an-hour, he adhered most conscientiously to his book, and would not even look at her.
}
